#!/usr/bin/env python3
"""
Bob-Sentry Triage Script — Script A (setup_realm.py)
Issue: #50445
CVE Pattern: CVE-2026-9796 (Class 10 sub-variant — Mapper Injection)
Assigned CVE: CVE-2026-4629
Attack Class Folder: .bob/reports/TOCTOU-role-rename/50445/
Generated by: Bob Code Mode
WARNING: This script targets http://localhost:8080 only.
         Do NOT execute against any remote or production instance.

Attack Summary:
  A user with manage-clients permission can create a HardcodedRole protocol mapper
  on any OIDC client. The mapper injects realm-admin into all tokens issued for that
  client at generation time, bypassing scope restrictions and granting full realm
  administrator privileges to any user who authenticates via the poisoned client.

Setup steps:
  1. Obtain master-realm admin token
  2. Create triage-realm
  3. Create triage-client (OIDC confidential, direct access grants on)
  4. Retrieve triage-client UUID
  5. Create triage-user (normal user, no elevated roles)
  6. Create delegated-admin user
  7. Grant delegated-admin the manage-clients role in triage-realm (NOT realm-admin)
  8. Verify delegated-admin does NOT already hold realm-admin
"""
import sys
import json
import requests

# ── Configuration ────────────────────────────────────────────────────────────
BASE_URL          = "http://localhost:8080"
REALM             = "triage-realm"
CLIENT_ID         = "triage-client"
CLIENT_SECRET     = "triage-secret"
ADMIN_USER        = "admin"
ADMIN_PASS        = "admin"
TEST_USER         = "triage-user"
TEST_PASS         = "triage-pass"
DELEGATED_ADMIN   = "delegated-admin"
DELEGATED_PASS    = "delegated-pass"
# ─────────────────────────────────────────────────────────────────────────────


def fail(msg):
    print(f"[ERROR] {msg}")
    print('RESULT: {"phase": "setup", "status": "failed", "reason": "' + msg + '"}')
    sys.exit(2)


# ── Step 1 — Admin token ─────────────────────────────────────────────────────
print("[SETUP] Obtaining admin token...", end=" ")
try:
    resp = requests.post(
        f"{BASE_URL}/realms/master/protocol/openid-connect/token",
        data={
            "grant_type": "password",
            "client_id": "admin-cli",
            "username": ADMIN_USER,
            "password": ADMIN_PASS,
        },
        timeout=15,
    )
    resp.raise_for_status()
except requests.exceptions.ConnectionError:
    fail("Cannot connect to Keycloak at localhost:8080 — is the container running?")
except requests.exceptions.HTTPError as e:
    fail(f"Admin token request failed: {e}")

admin_token = resp.json()["access_token"]
auth = {"Authorization": f"Bearer {admin_token}", "Content-Type": "application/json"}
print("OK")

# ── Step 2 — Create realm ────────────────────────────────────────────────────
print(f"[SETUP] Creating realm '{REALM}'...", end=" ")
resp = requests.post(
    f"{BASE_URL}/admin/realms",
    headers=auth,
    json={
        "realm": REALM,
        "enabled": True,
        "displayName": "Bob-Sentry Triage Realm",
        "registrationAllowed": False,
        "loginWithEmailAllowed": True,
        "duplicateEmailsAllowed": False,
        "resetPasswordAllowed": False,
        "editUsernameAllowed": False,
        "bruteForceProtected": False,
    },
    timeout=15,
)
if resp.status_code == 409:
    print("OK (already exists)")
elif resp.status_code == 201:
    print("OK")
else:
    fail(f"Create realm returned {resp.status_code}: {resp.text[:200]}")

# ── Step 3 — Create OIDC client ──────────────────────────────────────────────
print(f"[SETUP] Creating client '{CLIENT_ID}'...", end=" ")
resp = requests.post(
    f"{BASE_URL}/admin/realms/{REALM}/clients",
    headers=auth,
    json={
        "clientId": CLIENT_ID,
        "enabled": True,
        "protocol": "openid-connect",
        "publicClient": False,
        "secret": CLIENT_SECRET,
        "standardFlowEnabled": True,
        "directAccessGrantsEnabled": True,
        "serviceAccountsEnabled": False,
        "redirectUris": ["http://localhost:9999/*"],
        "webOrigins": ["http://localhost:9999"],
        "attributes": {
            "pkce.code.challenge.method": ""
        },
    },
    timeout=15,
)
if resp.status_code not in (201, 409):
    fail(f"Create client returned {resp.status_code}: {resp.text[:200]}")
print("OK")

# ── Step 4 — Resolve client UUID ─────────────────────────────────────────────
print(f"[SETUP] Resolving client UUID for '{CLIENT_ID}'...", end=" ")
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/clients",
    headers=auth,
    params={"clientId": CLIENT_ID},
    timeout=15,
)
resp.raise_for_status()
clients = resp.json()
if not clients:
    fail(f"Client '{CLIENT_ID}' not found after creation")
client_uuid = clients[0]["id"]
print(f"OK ({client_uuid})")

# ── Step 5 — Create triage-user ──────────────────────────────────────────────
print(f"[SETUP] Creating user '{TEST_USER}'...", end=" ")
resp = requests.post(
    f"{BASE_URL}/admin/realms/{REALM}/users",
    headers=auth,
    json={
        "username": TEST_USER,
        "enabled": True,
        "email": "triage-user@localhost.test",
        "firstName": "Triage",
        "lastName": "User",
        "credentials": [
            {"type": "password", "value": TEST_PASS, "temporary": False}
        ],
    },
    timeout=15,
)
if resp.status_code == 409:
    print("OK (already exists)")
elif resp.status_code == 201:
    print("OK")
else:
    fail(f"Create triage-user returned {resp.status_code}: {resp.text[:200]}")

# Resolve triage-user UUID
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/users",
    headers=auth,
    params={"username": TEST_USER, "exact": "true"},
    timeout=15,
)
resp.raise_for_status()
test_user_uuid = resp.json()[0]["id"]

# ── Step 6 — Create delegated-admin user ─────────────────────────────────────
print(f"[SETUP] Creating delegated admin user '{DELEGATED_ADMIN}'...", end=" ")
resp = requests.post(
    f"{BASE_URL}/admin/realms/{REALM}/users",
    headers=auth,
    json={
        "username": DELEGATED_ADMIN,
        "enabled": True,
        "email": "delegated-admin@localhost.test",
        "firstName": "Delegated",
        "lastName": "Admin",
        "credentials": [
            {"type": "password", "value": DELEGATED_PASS, "temporary": False}
        ],
    },
    timeout=15,
)
if resp.status_code == 409:
    print("OK (already exists)")
elif resp.status_code == 201:
    print("OK")
else:
    fail(f"Create delegated-admin returned {resp.status_code}: {resp.text[:200]}")

# Resolve delegated-admin UUID
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/users",
    headers=auth,
    params={"username": DELEGATED_ADMIN, "exact": "true"},
    timeout=15,
)
resp.raise_for_status()
delegated_admin_uuid = resp.json()[0]["id"]

# ── Step 7 — Grant manage-clients to delegated-admin ─────────────────────────
# manage-clients is a built-in client role on realm-management client
print(f"[SETUP] Granting 'manage-clients' role to '{DELEGATED_ADMIN}'...", end=" ")

# Find realm-management client UUID
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/clients",
    headers=auth,
    params={"clientId": "realm-management"},
    timeout=15,
)
resp.raise_for_status()
rm_clients = resp.json()
if not rm_clients:
    fail("realm-management client not found in triage-realm")
rm_client_uuid = rm_clients[0]["id"]

# Fetch the manage-clients role from realm-management
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/clients/{rm_client_uuid}/roles/manage-clients",
    headers=auth,
    timeout=15,
)
resp.raise_for_status()
manage_clients_role = resp.json()

# Assign manage-clients to delegated-admin
resp = requests.post(
    f"{BASE_URL}/admin/realms/{REALM}/users/{delegated_admin_uuid}"
    f"/role-mappings/clients/{rm_client_uuid}",
    headers=auth,
    json=[{"id": manage_clients_role["id"], "name": manage_clients_role["name"]}],
    timeout=15,
)
if resp.status_code not in (204, 409):
    fail(f"Assign manage-clients returned {resp.status_code}: {resp.text[:200]}")
print("OK")

# ── Step 8 — Verify delegated-admin does NOT hold realm-admin ────────────────
print(f"[SETUP] Verifying '{DELEGATED_ADMIN}' does NOT hold 'realm-admin'...", end=" ")
resp = requests.get(
    f"{BASE_URL}/admin/realms/{REALM}/users/{delegated_admin_uuid}/role-mappings/realm",
    headers=auth,
    timeout=15,
)
resp.raise_for_status()
realm_roles = [r["name"] for r in resp.json()]
if "realm-admin" in realm_roles:
    fail("PRECONDITION FAILED: delegated-admin already holds realm-admin — setup misconfigured")
print("OK (realm-admin absent — precondition satisfied)")

# ── Emit setup summary ────────────────────────────────────────────────────────
print(f"[SETUP] client_uuid={client_uuid}")
print(f"[SETUP] test_user_uuid={test_user_uuid}")
print(f"[SETUP] delegated_admin_uuid={delegated_admin_uuid}")
print(f"[SETUP] rm_client_uuid={rm_client_uuid}")
print("[SETUP] Environment ready. Proceeding to exploit phase.")
print(json.dumps({
    "phase": "setup",
    "status": "ready",
    "realm": REALM,
    "client_uuid": client_uuid,
    "test_user_uuid": test_user_uuid,
    "delegated_admin_uuid": delegated_admin_uuid,
    "rm_client_uuid": rm_client_uuid,
}))
print('RESULT: {"phase": "setup", "status": "ready", "realm": "triage-realm"}')
