#!/usr/bin/env python3
"""
Bob-Sentry Triage Script -- Script A (v2)
Issue: #50981
CVE Pattern: CVE-2026-11986
Attack Class Folder: .bob/reports/FGAP-assign-unassign/50981/
Generated by: Bob Code Mode
WARNING: This script targets http://localhost:8080 only.
         Do NOT execute against any remote or production instance.

VULNERABILITY CLAIM:
  Delegated user administrators with FGAP v2 view-users permission (but NO view-clients)
  can enumerate hidden client UUIDs, clientIds, session participation, offline-token
  grants, and consent metadata through user subresource endpoints:
    GET /admin/realms/{realm}/users/{userId}/sessions
    GET /admin/realms/{realm}/users/{userId}/offline-sessions/{clientUuid}
    GET /admin/realms/{realm}/users/{userId}/consents

SETUP DESIGN:
  1. Create triage-realm.
  2. Create a hidden confidential client (triage-secret-client) with consentRequired=false
     so that direct access grants work and we can create a real session.
     (The vulnerability is about the Admin API leaking client data, not about consent.)
  3. Create a public OIDC client (triage-client) for token acquisition.
  4. Create a victim user (triage-victim) who has a session + offline token
     against the hidden client (authenticated via direct access grants).
  5. Create a delegated admin (triage-viewer) granted ONLY view-users from
     realm-management. NO view-clients, NO manage-clients.
  6. Baseline: confirm triage-viewer cannot see triage-secret-client directly.

NOTE: After session creation, we add a consent record manually via Admin API so
      the consents endpoint has data to potentially leak.
"""

import sys
import time
import json
import urllib.request
import urllib.parse
import urllib.error

# -- Configuration ------------------------------------------------------------
BASE          = "http://localhost:8080"
ADMIN_USER    = "admin"
ADMIN_PASS    = "admin"
REALM         = "triage-realm"
PUB_CLIENT    = "triage-client"
SECRET_CLIENT = "triage-secret-client"
VICTIM_USER   = "triage-victim"
VICTIM_PASS   = "triage-pass"
VIEWER_USER   = "triage-viewer"
VIEWER_PASS   = "triage-pass"
# -----------------------------------------------------------------------------


def req(method, url, data=None, token=None, ct="application/json"):
    body = None
    if data is not None:
        body = (urllib.parse.urlencode(data).encode()
                if ct == "application/x-www-form-urlencoded"
                else json.dumps(data).encode())
    r = urllib.request.Request(url, data=body, method=method)
    r.add_header("Content-Type", ct)
    if token:
        r.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(r) as resp:
            raw = resp.read()
            return resp.status, (json.loads(raw) if raw else {})
    except urllib.error.HTTPError as e:
        raw = e.read()
        try:
            return e.code, json.loads(raw)
        except Exception:
            return e.code, raw.decode(errors="replace")


def admin_token():
    s, b = req("POST", f"{BASE}/realms/master/protocol/openid-connect/token",
               data={"grant_type": "password", "client_id": "admin-cli",
                     "username": ADMIN_USER, "password": ADMIN_PASS},
               ct="application/x-www-form-urlencoded")
    assert s == 200, f"Admin token failed: {s} {b}"
    print("[SETUP] Admin token obtained.")
    return b["access_token"]


def main():
    print("[SETUP] Waiting for Keycloak to be ready...")
    for i in range(36):
        try:
            urllib.request.urlopen(f"{BASE}/realms/master", timeout=3)
            print("[SETUP] Keycloak is ready.")
            break
        except Exception:
            if i == 35:
                print("[SETUP] ERROR: Keycloak not ready after 3 minutes.")
                sys.exit(2)
            time.sleep(5)

    tok = admin_token()

    # -- Realm -----------------------------------------------------------------
    s, _ = req("POST", f"{BASE}/admin/realms",
               data={"realm": REALM, "enabled": True}, token=tok)
    assert s in (201, 409), f"Create realm: {s}"
    print(f"[SETUP] Realm '{REALM}': {'created' if s == 201 else 'already exists'}.")

    # -- Public client for token acquisition -----------------------------------
    s, _ = req("POST", f"{BASE}/admin/realms/{REALM}/clients",
               data={"clientId": PUB_CLIENT, "enabled": True, "publicClient": True,
                     "directAccessGrantsEnabled": True,
                     "redirectUris": ["http://localhost:9999/*"]}, token=tok)
    assert s in (201, 409), f"Create pub client: {s}"
    print(f"[SETUP] Public client '{PUB_CLIENT}': {'created' if s == 201 else 'already exists'}.")

    # -- Hidden confidential client --------------------------------------------
    # consentRequired=false so directAccessGrants work (we test the Admin API leak, not consent UI)
    s, _ = req("POST", f"{BASE}/admin/realms/{REALM}/clients",
               data={"clientId": SECRET_CLIENT,
                     "enabled": True,
                     "publicClient": False,
                     "directAccessGrantsEnabled": True,
                     "consentRequired": False,
                     "standardFlowEnabled": True,
                     "redirectUris": ["http://localhost:9999/secret"],
                     "description": "Confidential client intentionally hidden from delegated admin"},
               token=tok)
    assert s in (201, 409), f"Create secret client: {s}"
    print(f"[SETUP] Hidden client '{SECRET_CLIENT}': {'created' if s == 201 else 'already exists'}.")

    s, clients = req("GET", f"{BASE}/admin/realms/{REALM}/clients?clientId={SECRET_CLIENT}", token=tok)
    assert s == 200 and clients, f"Secret client UUID lookup: {s}"
    secret_uuid = clients[0]["id"]
    print(f"[SETUP] '{SECRET_CLIENT}' UUID: {secret_uuid}")

    # -- Victim user -----------------------------------------------------------
    s, _ = req("POST", f"{BASE}/admin/realms/{REALM}/users",
               data={"username": VICTIM_USER, "enabled": True,
                     "firstName": "Triage", "lastName": "Victim",
                     "email": "triage-victim@test.local",
                     "emailVerified": True, "requiredActions": [],
                     "credentials": [{"type": "password",
                                      "value": VICTIM_PASS, "temporary": False}]},
               token=tok)
    assert s in (201, 409), f"Create victim user: {s}"
    print(f"[SETUP] Victim user '{VICTIM_USER}': {'created' if s == 201 else 'already exists'}.")

    s, users = req("GET", f"{BASE}/admin/realms/{REALM}/users?username={VICTIM_USER}", token=tok)
    assert s == 200 and users
    victim_uuid = users[0]["id"]
    print(f"[SETUP] '{VICTIM_USER}' UUID: {victim_uuid}")

    # -- Delegated admin (view-users ONLY) -------------------------------------
    s, _ = req("POST", f"{BASE}/admin/realms/{REALM}/users",
               data={"username": VIEWER_USER, "enabled": True,
                     "firstName": "Triage", "lastName": "Viewer",
                     "email": "triage-viewer@test.local",
                     "emailVerified": True, "requiredActions": [],
                     "credentials": [{"type": "password",
                                      "value": VIEWER_PASS, "temporary": False}]},
               token=tok)
    assert s in (201, 409), f"Create viewer user: {s}"
    print(f"[SETUP] Delegated admin '{VIEWER_USER}': {'created' if s == 201 else 'already exists'}.")

    s, users = req("GET", f"{BASE}/admin/realms/{REALM}/users?username={VIEWER_USER}", token=tok)
    viewer_uuid = users[0]["id"]

    # Grant ONLY view-users from realm-management (NO view-clients)
    s, rm_clients = req("GET", f"{BASE}/admin/realms/{REALM}/clients?clientId=realm-management", token=tok)
    rm_uuid = rm_clients[0]["id"]

    s, vu_role = req("GET", f"{BASE}/admin/realms/{REALM}/clients/{rm_uuid}/roles/view-users", token=tok)
    assert s == 200, f"view-users role lookup: {s}"

    s, _ = req("POST",
               f"{BASE}/admin/realms/{REALM}/users/{viewer_uuid}/role-mappings/clients/{rm_uuid}",
               data=[vu_role], token=tok)
    assert s in (204, 409), f"Assign view-users: {s}"
    print(f"[SETUP] Granted ONLY 'view-users' to '{VIEWER_USER}' (view-clients withheld).")

    # -- Get the hidden client secret -----------------------------------------
    s, cred_data = req("GET", f"{BASE}/admin/realms/{REALM}/clients/{secret_uuid}/client-secret", token=tok)
    assert s == 200, f"Get client secret: {s}"
    client_secret_val = cred_data.get("value", "")

    # -- Victim login against hidden client (creates user session) -------------
    vs, vb = req("POST", f"{BASE}/realms/{REALM}/protocol/openid-connect/token",
                 data={"grant_type": "password", "client_id": SECRET_CLIENT,
                       "client_secret": client_secret_val,
                       "username": VICTIM_USER, "password": VICTIM_PASS,
                       "scope": "openid"},
                 ct="application/x-www-form-urlencoded")
    print(f"[SETUP] Victim login via hidden client: HTTP {vs}")
    if vs != 200:
        print(f"[SETUP] WARNING: victim session creation returned {vs}: {vb}")

    # -- Victim offline token against hidden client ----------------------------
    os_status, ob = req("POST", f"{BASE}/realms/{REALM}/protocol/openid-connect/token",
                        data={"grant_type": "password", "client_id": SECRET_CLIENT,
                              "client_secret": client_secret_val,
                              "username": VICTIM_USER, "password": VICTIM_PASS,
                              "scope": "offline_access openid"},
                        ct="application/x-www-form-urlencoded")
    print(f"[SETUP] Victim offline token via hidden client: HTTP {os_status}")
    if os_status != 200:
        print(f"[SETUP] WARNING: offline token creation returned {os_status}: {ob}")

    # -- Baseline: viewer CANNOT directly access the hidden client ------------
    s, vr_tok_body = req("POST", f"{BASE}/realms/{REALM}/protocol/openid-connect/token",
                         data={"grant_type": "password", "client_id": PUB_CLIENT,
                               "username": VIEWER_USER, "password": VIEWER_PASS},
                         ct="application/x-www-form-urlencoded")
    assert s == 200, f"Viewer token: {s}"
    v_tok = vr_tok_body["access_token"]

    baseline_s, _ = req("GET", f"{BASE}/admin/realms/{REALM}/clients/{secret_uuid}", token=v_tok)
    if baseline_s == 403:
        print(f"[SETUP] BASELINE OK: viewer cannot read hidden client via /clients/{{id}} (403). OK")
    else:
        print(f"[SETUP] WARNING: baseline returned {baseline_s} (expected 403).")

    # -- Persist state --------------------------------------------------------
    state = {
        "secret_uuid": secret_uuid,
        "victim_uuid": victim_uuid,
        "viewer_uuid": viewer_uuid,
        "rm_uuid": rm_uuid,
        "baseline_direct_status": baseline_s,
        "victim_session_created": (vs == 200),
        "victim_offline_token_created": (os_status == 200),
    }
    with open("/tmp/keycloak-triage/state.json", "w") as f:
        json.dump(state, f)

    print()
    print("[SETUP] Setup complete.")
    print(f"[SETUP]   Viewer:        {VIEWER_USER}/{VIEWER_PASS} (view-users ONLY -- no view-clients)")
    print(f"[SETUP]   Hidden client: {SECRET_CLIENT} (uuid={secret_uuid})")
    print(f"[SETUP]   Victim:        {VICTIM_USER} (session={vs==200}, offline={os_status==200})")
    print(f"[SETUP]   Baseline:      direct GET /clients/{{id}} -> {baseline_s} (expect 403)")
    print()
    print('RESULT: {"phase": "setup", "status": "ready", "realm": "triage-realm"}')


if __name__ == "__main__":
    main()
